### PR TITLE
fixed some bugs + fixed email ui

### LINKED ISSUE #29: Finish emails UI

### PR DESCRIPTION
**Pull request by MishaFomenko**
I fixed some bugs here&there:
- added hash to confirmation emails;
- added two appointments' info into hash for rescheduling
- moved deleting ignored confirmation appointments to appointment-svc (added another method to appointmentController)
Fixed emails UI
fixes #29

### CODE REVIEW

File: appointment-svc/controllers/appointment-controller.ts [hunk 1]
```diff
@@ -176,6 +184,26 @@ class AppoinmentController {
     }
   }
 
+  async deleteMany(req: Request, res: Response, next: NextFunction) {
+    const ignoredIds = req.body
+    const condition = {
+      where: {
+        id: ignoredIds
+      }
+    }
```
Comment (vlad-lychak) [inline appointment-svc/controllers/appointment-controller.ts]: Why did you transfer the condition in this file?

File: appointment-svc/router/index.ts [hunk 2]
```diff
@@ -37,6 +37,12 @@ router.delete(
   appointmentController.deleteOne
 );
 
+router.delete(
+  '/appointment',
+  authMiddleware(),
```
Comment (vlad-lychak) [inline appointment-svc/router/index.ts]: I think you meant '/appointments'

File: appointment-svc/controllers/appointment-controller.ts [hunk 3]
```diff
@@ -176,6 +184,26 @@ class AppoinmentController {
...
+    const ignoredAppointments = await AppointmentRepository.getMany(condition)
+
+    try {
+      ignoredAppointments.forEach(async (appointment) => {
+        await AppointmentRepository.deleteOne(appointment.id)
+      })
```
Comment (vlad-lychak) [inline appointment-svc/controllers/appointment-controller.ts]: Instead of first fetching all the appointments and then deleting all appointments 1 by 1, we can just create a new database call with deleteMany and pass a list of IDs.

File: appointment-svc/service/db-service/AppointmentRepository.ts [hunk 4]
```diff
@@ -20,19 +20,9 @@ class AppointmentRepository {
     return appointments;
   }
 
-  async getBooked(queryMaxDate: string, queryMinDate: string) {
+  async getMany(condition: Object) {
     const appointmentsToConfirm = await prisma.appointment.findMany({
```
Comment (vlad-lychak) [inline appointment-svc/service/db-service/AppointmentRepository.ts]: What's with the type definition?

File: notification-svc/views/confirmationEmail.ts
Comment (vlad-lychak) [inline notification-svc/views/confirmationEmail.ts:1]: Good idea to separate templates!

**Review by deepu-premrajan — APPROVED** [review]
